// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wkblxoqjpbooigygijbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndrYmx4b3FqcGJvb2lneWdpamJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTk1NTksImV4cCI6MjA2NTE5NTU1OX0.pXOHpDabAb4IHaKwUj75jqM79Ph9IdRus7VjjoeYpDY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);